### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#10]
1. Ссылки в два ряда выглядят не очень, или уменьшать шрифт, или убирать в меню.
![не очень](https://user-images.githubusercontent.com/51824674/85200667-3604e200-b31b-11ea-88ec-82345264da9e.png)

2. Кнопки в два ряда тоже так себе.
![не очень1](https://user-images.githubusercontent.com/51824674/85200688-6b113480-b31b-11ea-8ffe-99b39f9a67a2.png)

3. Иконки переносятся на следующую строку, при нажатии на иконку ничего не происходит.
![Screenshot from 2020-06-20 16-34-17](https://user-images.githubusercontent.com/51824674/85200709-91cf6b00-b31b-11ea-87e6-a853362c601e.png)

4. Текст в инпутах скрывается, надо уменьшать, на датах тоже проверить.
![текст](https://user-images.githubusercontent.com/51824674/85200734-ca6f4480-b31b-11ea-8e13-210dd84d1ee1.png)

5. Рано убирается третий столбец.
![рано](https://user-images.githubusercontent.com/51824674/85200767-f094e480-b31b-11ea-9fa5-466d8dc05972.png)

6. Пагинация не центрируется.
![центр](https://user-images.githubusercontent.com/51824674/85200803-1fab5600-b31c-11ea-9b71-23d1461a0da8.png)

7. Элементы слишком близко.
![близ](https://user-images.githubusercontent.com/51824674/85200814-4073ab80-b31c-11ea-9dd5-e1ea49e93c87.png)
![близко](https://user-images.githubusercontent.com/51824674/85200816-46698c80-b31c-11ea-8fa5-458cfa75790b.png)

8. Не центрируется.
![не по центру, отступ](https://user-images.githubusercontent.com/51824674/85200824-571a0280-b31c-11ea-8088-666e7e25985e.png)

9. Число переносится на вторую строку.
![отображение](https://user-images.githubusercontent.com/51824674/85200842-7b75df00-b31c-11ea-8259-7534b66b6cb2.png)

10. Большие вертикальные отступы у карточки.
![отступ](https://user-images.githubusercontent.com/51824674/85200858-96485380-b31c-11ea-9c47-ef9f116cbe87.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. На разрешении больше 1440px колонка со слайдерами сжимается.
![shrink](https://user-images.githubusercontent.com/51824674/85741705-7782fc00-b724-11ea-9b7a-aebd082c9d8f.png)
2. Подвал, и содержимое, например, лэндинга на большем разрешении шире стандартного контейнера, при этом шапка остается в его рамках, или растягивать все, или ничего, кроме фона.
![out of container](https://user-images.githubusercontent.com/51824674/85742217-e19ba100-b724-11ea-815a-4cfcbdbbdae4.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Overlay не очень, а если добавлять дополнительные отступы, то надо учитывать,  что на firefox overlay не работает
![Screenshot from 2020-06-27 11-33-26](https://user-images.githubusercontent.com/51824674/85915931-98a33400-b86d-11ea-85d5-61e47d1e4106.png)

2. В любом случае, отступы добавить надо, потому что на меньших разрешениях они есть, на больших нет
![paddings](https://user-images.githubusercontent.com/51824674/85915946-c5efe200-b86d-11ea-8152-e3c3f485341f.png)

3. Карточки на регистрации и входе прижимаются к краям экрана
![Screenshot from 2020-06-27 11-36-17](https://user-images.githubusercontent.com/51824674/85915975-ef107280-b86d-11ea-9be4-9d51e01334a3.png)

4. Календарь на малых разрешениях не адаптируется.

5. У карточек нет границы(теней).
![shadows](https://user-images.githubusercontent.com/51824674/85916008-2bdc6980-b86e-11ea-94bb-ec3605657750.png)

**Comment by wirwl** [comment]
Убрал я **overflow: overlay**, вёрстка ломается слишком сильно, думал поинтересней результат будет - овчинка выделки не стоит!

Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. На ширине примерно 1442px - 1515px (смотреть на реальном браузере, не device toggle tool bar) одна картинка уходит ниже.
![1442](https://user-images.githubusercontent.com/51824674/86133620-5cd8ca80-bb0a-11ea-82bd-a8914918d714.png)

2. Выровняй карточку по контейнеру.
![Screenshot from 2020-06-30 18-58-26](https://user-images.githubusercontent.com/51824674/86133692-7a0d9900-bb0a-11ea-969e-f89fae76addc.png)

3. Слишком большие отступы, на втором скрине нижнего отступа тоже касается.
![offset](https://user-images.githubusercontent.com/51824674/86133803-9e697580-bb0a-11ea-8c47-9a11a896800d.png)
![Screenshot from 2020-06-30 19-39-26](https://user-images.githubusercontent.com/51824674/86133811-a0cbcf80-bb0a-11ea-9c5a-1ab615b3ff94.png)

4. Здесь переносить отзывы пикселей на 40 раньше и отступ сверху сделать больше.
![Screenshot from 2020-06-30 19-31-49](https://user-images.githubusercontent.com/51824674/86133921-c8229c80-bb0a-11ea-8e06-083d07e43167.png)

5. Здесь между отменой и правилами также сделать отступ больше 
![Screenshot from 2020-06-30 19-33-32](https://user-images.githubusercontent.com/51824674/86134011-e8525b80-bb0a-11ea-870d-1fbaf3b88e73.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Верхний отступ сделать меньше, нижний больше, примерно равными.
![more less](https://user-images.githubusercontent.com/51824674/86327584-5f036c00-bc65-11ea-97b0-2c70a0a6151d.png)

2. Отступы уменьшить раз в пять.
![offset](https://user-images.githubusercontent.com/51824674/86327711-89edc000-bc65-11ea-9552-ac2ddae9a4a9.png)

3. Шапка с подвалом стали поздно сворачиваться.
![Screenshot from 2020-07-02 12-50-05](https://user-images.githubusercontent.com/51824674/86327780-9eca5380-bc65-11ea-8f8e-57fb2aa5d335.png)

4. На определенном отрезке пропадают боковые отступы
![sticky](https://user-images.githubusercontent.com/51824674/86327869-c02b3f80-bc65-11ea-9296-9bed72720cd6.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Здесь до сих пор большой отступ
![Screenshot from 2020-07-03 09-43-09](https://user-images.githubusercontent.com/51824674/86429758-4d2bd280-bd12-11ea-8486-36a7a072d911.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
