### ISSUE TITLE
Навигация по страницам

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#11]
Нужно добавить навигацию между страницами:

- логотипы в хедере (как например этот) обычно ведут на главную страницу проекта
![image](https://user-images.githubusercontent.com/46089168/92734392-2d9fce80-f381-11ea-9f49-92c99eb1199c.png)
- вот эти кнопки должны вести на страницы входа/регистрации
![image](https://user-images.githubusercontent.com/46089168/92734660-69d32f00-f381-11ea-9362-c78e0646cbd0.png)

Возможно, есть еще, глянь пожалуйста по всем подобным местам

**Comment by wirwl** [comment]
Исправил, можно проверять.
