### ISSUE TITLE
Оптимизация

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#12]
Сейчас после сборки на страницу подгружается 1 js-файл, в котором вообще всё лежит. Это не очень эффективно, потому что при таком подходе пользователь при открытии каждой новой странички сайта подгружает jquery и прочие общие библиотеки заново в еще одном большом js-файле, хотя на самом деле нового кода там гораздо меньше. Было бы очень здорово вынести тот же jquery в отдельный файл типа vendors.js/common.js. Попробуй настроить code splitting:
https://webpack.js.org/guides/code-splitting/

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
А почему пути теперь типа такого, когда нужно напрямую в папку node_modules лезть?
` import '../../../node_modules/air-datepicker/dist/js/datepicker'; `

Вот так нельзя разве? 
` import 'air-datepicker/dist/js/datepicker'; `

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
> Вот так нельзя разве?
> `import 'air-datepicker/dist/js/datepicker';`

Я просто не знал что так можно писать, теперь буду знать.))
