### ISSUE TITLE
Структура

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#13]
Мне кажется, этим миксинам не место в файле common.pug, так как они относятся только к хедеру, лучше их куда-нибудь к нему поближе убрать на мой взгляд. Как вариант, можешь создать папку utils в компоненте header-menu и туда их сложить, ну или еще что-то придумай
![image](https://user-images.githubusercontent.com/46089168/92737085-85d7d000-f383-11ea-9ffe-74813290a286.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
