### ISSUE TITLE
Компонент подписки

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#14]
Подразумевается, что это все же не просто картинка в инпуте, а кнопка для отправки, иначе подписаться не получится никак) Кстати, инпут еще надо в форму обернуть
![image](https://user-images.githubusercontent.com/46089168/92737973-3940c480-f384-11ea-9bf0-e3b30a2edbe3.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
1. Сейчас получается, что стрелочка это псевдоэлемент всей формы, а кнопка идет отдельно от нее. Мне кажется, что они всё же связаны, стрелочка только в кнопке имеет смысл, поэтому лучше псевдоэлемент кнопки использовать, а не всего поля, а еще так будет удобнее в пределах кнопки ее позиционировать

2. Лучше не задавать в данном случае ширину кнопки в % от всего поля, потому что если я захочу растянуть компонент, растянется и кнопка, что не очень здорово и вряд ли так подразумевалось
![image](https://user-images.githubusercontent.com/46089168/93579189-dc0dca00-f9a6-11ea-80b8-e2a8efd52bb1.png)

3. Сейчас паддинга не хватает, текст налезает на кнопку. Саму кнопку лучше квадратной сделать, сейчас она по ширине чуть меньше, несимметрично как-то)
![image](https://user-images.githubusercontent.com/46089168/93578544-204c9a80-f9a6-11ea-9146-5ce848bee343.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
