### ISSUE TITLE
Семантика

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#15]
Есть проблемы с заголовками:
- заголовков h1 почти нигде нет
- есть прыжки через уровни, например h1 нет, а h2 есть, такого быть не должно, заголовки по уровням должны друг за другом идти
- в некоторых местах не очень удачное использование, например в этой карточке бронирования. У тебя тут итого и сама цена это h2. Мне кажется, что лучше было бы в h2 обернуть цифры номера в начале карточки, либо сделать специальный заголовок "Бронирование номера №..." и скрыть его через css
![image](https://user-images.githubusercontent.com/46089168/92740680-9dfd1e80-f386-11ea-8e63-882e0802ec40.png)

Пройдись пожалуйста по всему проекту, посмотри, везде ли стоят заголовки и правильно ли они стоят, или можно сделать как-то удачнее по смыслу

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
- На странице должен быть 1 заголовок h1, а например на странице с деталями номера их аж 5
![image](https://user-images.githubusercontent.com/46089168/93580155-1166e780-f9a8-11ea-8817-a13e3a2380fb.png)

- вот тут и номер, и заголовки полей одного уровня, может лучше сделать номер h2, а остальные h3?
![image](https://user-images.githubusercontent.com/46089168/93580373-63a80880-f9a8-11ea-9ea7-9114afe1f740.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Через display: none; заголовки лучше не скрывать, их в таком случае нет на странице, в том числе и для читалок/скринридеров. Почитай про visually-hidden

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Не стоит дублировать по всему проекту тело этого класса, вместо этого лучше завести миксин visually-hidden и подключать его в компоненты

**Comment by wirwl** [comment]
Исправил, можно проверять.
