### ISSUE TITLE
Значения по умолчанию

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#16]
Лучше задавать в таких местах значения по умолчанию (например здесь можно [] задать), чтобы не крашилось всё приложение, если вдруг не прокинуть список туда
![image](https://user-images.githubusercontent.com/46089168/93582063-a074ff00-f9aa-11ea-8fc9-443dfbb5d797.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Кое-где еще нет значений по умолчанию
![image](https://user-images.githubusercontent.com/46089168/93802569-4eeb9f00-fc4c-11ea-99f3-c2d9ee32eb31.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
