### ISSUE TITLE
Стайлгайд/кодгайд

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#17]
1. В стилях местами встречаются двойные кавычки, нужно на одинарные поменять 
(https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/generalRequirements.md пункт 2)

2. Лучше все же исправить ` :before ` на ` ::before `, с одним двоеточием для совместимости оставлено, в CSS3 уже с двумя используется

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Вместо 0px лучше просто 0 писать, текущий вариант стайллинту не очень нравится
![image](https://user-images.githubusercontent.com/46089168/93998982-f1676780-fd9d-11ea-9e2e-063d2f44e66d.png)

**Comment by Fr0stmourne** [comment]
не стоит умещать if вместе с else блоком на одну строчку, из-за этого код читается сильно хуже
![image](https://user-images.githubusercontent.com/46089168/94002599-c6cbdd80-fda2-11ea-9d4e-c9a4a4e9375e.png)

**Comment by Fr0stmourne** [comment]
Тут тоже тяжеловато читается. Я так понимаю, 2, 3, 6 и прочие числа это количество страниц, на которое завязана логика по переключению. Если так, то лучше их вынести в константы или даже создать объект-конфиг, где это описать, потому что если я например захочу сейчас уменьшить количество страниц на 1, придется долго разбираться в коде
![image](https://user-images.githubusercontent.com/46089168/94004238-0f849600-fda5-11ea-8d7e-6195a08f3340.png)

**Comment by Fr0stmourne** [comment]
![image](https://user-images.githubusercontent.com/46089168/94004581-93d71900-fda5-11ea-9a47-07cb34655051.png)
Привязывать контекст лучше в конструкторе в отдельном методе, а еще лучше использовать декоратор autobind, потому что не очень удобно, когда привязки раскиданы по разным методам, несмотря на то, что они будут вызваны в конструкторе

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Привязки контекста не поправил

**Comment by Fr0stmourne** [comment]
Еще местами есть странные переопределения свойств типа такого
![image](https://user-images.githubusercontent.com/46089168/94419906-0cfeb380-018c-11eb-8d5c-bec874ab511e.png)

**Comment by Fr0stmourne** [comment]
Вот так лучше не сокращать, это уже хуже читается и ищется по проекту
![image](https://user-images.githubusercontent.com/46089168/94421237-f3f70200-018d-11eb-8051-e687289adfc0.png)

Если очень хочется сокращать, то лучше уже тогда так, хотя я бы все же не советовал
```
&_header {
         &_one {}
         &_two {}
}

**Comment by Fr0stmourne** [comment]
Такие ненужные куски кода надо подчистить
![image](https://user-images.githubusercontent.com/46089168/94421724-a4fd9c80-018e-11eb-9c13-9dde29372dc6.png)

**Comment by Fr0stmourne** [comment]
В стилях слайдера есть огромные селекторы, зачем там такая специфичность нужна?
![image](https://user-images.githubusercontent.com/46089168/94422391-ada2a280-018f-11eb-92ad-d34aacb576e0.png)

**Comment by wirwl** [comment]
> В стилях слайдера есть огромные селекторы, зачем там такая специфичность нужна?
> ![image](https://user-images.githubusercontent.com/46089168/94422391-ada2a280-018f-11eb-92ad-d34aacb576e0.png)

Убрал 1 селектор. Остальные нужны для правильного функционирования слайдера.
Надо модифицировать лейбел: **.image-slider__label** если input:checked. Поэтому через + обращаемся к соседу справа (.image-slider__container) и далее к потомку **.image-slider__label**

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
- Странные относительные величины по-прежнему встречаются
![image](https://user-images.githubusercontent.com/46089168/94570353-70b1db00-0277-11eb-8833-f65531fa3ed6.png)

- По привязки я вообще имел в виду запись типа ` this.method = this.method.bind(this) ` для обработчиков, все такие методы надо привязать в отдельном методе и вызвать этот метод в конструкторе. Тогда при навешивании обработчиков их в каждом месте не надо будет отдельно привязывать

**Comment by wirwl** [comment]
Исправил, можно проверять.
