### ISSUE TITLE
Страница Search-room

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#19]
Выбор дат съехал на странице search-room
![image](https://user-images.githubusercontent.com/46089168/93803964-44caa000-fc4e-11ea-861c-355c484352e4.png)

**Comment by Fr0stmourne** [comment]
Пространство между бегунками не полностью заполнено, сверху есть полоска в пару пикселей
![image](https://user-images.githubusercontent.com/46089168/93804173-97a45780-fc4e-11ea-9bcf-75cc88180540.png)

**Comment by wirwl** [comment]
> Пространство между бегунками не полностью заполнено, сверху есть полоска в пару пикселей
> ![image](https://user-images.githubusercontent.com/46089168/93804173-97a45780-fc4e-11ea-9bcf-75cc88180540.png)

У меня такой проблемы не наблюдается. Может у тебя просто масштаб не 100% а 110%, например?

**Comment by wirwl** [comment]
Исправил, можно проверять.
