### ISSUE TITLE
Шрифты, картинки

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#2]
![Снимок экрана от 2020-04-15 16-14-16](https://user-images.githubusercontent.com/51824674/79326409-9f8bfd00-7f34-11ea-8c42-e5e03bc86897.png)

**Comment by wirwl** [comment]
Всё просмотрел. Всё вроде  в стиле "нижний регистр, через дефис", можешь конкретное место показать где не так?

**Comment by wirwl** [comment]
Исправил.

**Comment by iatsdotfatr** [comment]
Гит по умолчанию изменения в регистре не замечает.

**Comment by wirwl** [comment]
Всё исправил, можно проверять. Сейчас залью на github.io

**Comment by iatsdotfatr** [comment]
![lower-case-hyphenated](https://user-images.githubusercontent.com/51824674/79870115-aae79880-840c-11ea-8ec9-e2fc2626c55a.png)

**Comment by wirwl** [comment]
Исправил.
