### ISSUE TITLE
Радио-кнопки

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#20]
Кружок внутри спозиционирован не совсем по центру:
![image](https://user-images.githubusercontent.com/46089168/93804873-90ca1480-fc4f-11ea-844a-10b92dba433b.png)
Я бы посоветовал сделать внешнюю обводку радио-инпута сделать отдельным элементом и для него задавать псевдоэлементу стили подобным образом:
```
left: 50%;
top: 50%;
transform: translate(-50%, -50%);
```
При таком подходе: 
1. Кружок внутри всегда будет ровно по центру и не придется долго подбирать пиксели
2. Если понадобится изменить размеры радиокнопки, не придется заново позиционировать этот кружок внутри

**Comment by wirwl** [comment]
> Кружок внутри спозиционирован не совсем по центру:
> ![image](https://user-images.githubusercontent.com/46089168/93804873-90ca1480-fc4f-11ea-844a-10b92dba433b.png)

У меня такой проблемы не наблюдается. Может у тебя просто масштаб не 100% а 110%, например?

**Comment by wirwl** [comment]
Исправил, можно проверять.
