### ISSUE TITLE
Отступ последнего элемента

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#21]
В списках лучше margin для последнего элемента обнулять, потому что после него уже нет других элементов и таким образом внешний отступ у всего блока появляется
![image](https://user-images.githubusercontent.com/46089168/93999338-5c18a300-fd9e-11ea-87c5-18fde18f6da9.png)

Лучше писать что-то вроде такого:
```
&__item:not(:last-child) {
    margin-bottom: 10px;
  }
```

или 

```
&__item {
    margin-bottom: 10px;
  }

&__item:last-child {
    margin-bottom: 0;
  }

**Comment by wirwl** [comment]
Исправил, можно проверять.
