### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#22]
Сейчас в проекте есть классы типа `button-bordered_dynamic-width`, мне кажется, что тут ты пытаешься сказать, что есть width и значение у нее dynamic. Если это так, то лучше писать  `button-bordered_width_dynamic`

https://ru.bem.info/methodology/quick-start/#%D0%BC%D0%BE%D0%B4%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80

**Comment by Fr0stmourne** [comment]
Еще нашел вот такое:
![image](https://user-images.githubusercontent.com/46089168/94002991-4e195100-fda3-11ea-8896-6e8c52663f2d.png)
Если ты используешь модификатор одним словом, то это должно быть прилагательное/причастие (тут это было бы hidden например, а не hide)
Проверь еще раз все модификаторы по проекту

**Comment by wirwl** [comment]
Исправил, можно проверять.
