### ISSUE TITLE
Кнопки

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#23]
- Сейчас в проекте эти 2 типа кнопок это отдельные компоненты:
![image](https://user-images.githubusercontent.com/46089168/94001119-bb77b280-fda0-11ea-82d7-4ce5aa4ebb9d.png)

Это не очень удобно, потому что там меняется только цветовое оформление, а многие стили между компонентами дублируются. Лучше их объединить в один компонент и передавать туда тип кнопки типа filled, bordered. Можно даже в тот же компонент завернуть кнопку со стрелкой, так как там по сути только она и добавляется, а другие стили от filled, но тут на твое усмотрение

- Думаю, тут проверка эта уже лишняя, раз определено по умолчанию значение
![image](https://user-images.githubusercontent.com/46089168/94001459-350fa080-fda1-11ea-9a04-95bb940eb49b.png)

Еще небольшой коммент по js, там тернарник в принципе без особой надобности по идее, я бы переписал следующим образом:
```
onclick = href && window.location.href='${href}' 
```
- onClick не нужно использовать, чтобы кнопку превратить ссылку, это плохой подход. Казалось бы, это ссылка, я хочу открыть ее в новой вкладке например, но я не могу, потому что это под капотом кнопка с onclick. 
![image](https://user-images.githubusercontent.com/46089168/94001894-d565c500-fda1-11ea-84a1-0523626cca7d.png)
Если это ссылка, надо использовать ссылку, как бы банально это не звучало) В этом компоненте можно смотреть, определен ли href (параметр по умолчанию для него я бы не задавал), и на основании этого создавать либо кнопку, либо ссылку

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Модификатор кнопки `button_header` выглядит довольно странно, такая же кнопка может не только в хедере использоваться, вообще не должно быть в компоненте упоминаний о месте его использования, он по идее переиспользуемый и ни с чем другим не связан. Здесь лучше отделить по другому параметру (как вариант, форма кнопки)
![image](https://user-images.githubusercontent.com/46089168/94420211-81d1ed80-018c-11eb-8c97-77004b3f285d.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
