### ISSUE TITLE
Инициализация JS

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#25]
Лучше вместо вызова класса прямо в файле с жестко зашитым классом экспортировать класс и на нужных страницах его импортировать и подключать, в текущем варианте придется дополнительно править компонент, если вдруг понадобится подключить с другим классом функциональность
![image](https://user-images.githubusercontent.com/46089168/94419624-babd9280-018b-11eb-8c4d-c91bf2c012fd.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Эту разметку надо зашить в класс, сейчас при подключении к каждой новой странице приходится копипастить одно и то же, это максимально неудобно, если надо будет эту разметку изменить
![image](https://user-images.githubusercontent.com/46089168/94573244-92609180-027a-11eb-9831-0630276d37c0.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Заметил, что уже в js-файлах страниц встречаются подобные куски, добавляющие какие-то обработчики/логику к компонентам, почему это именно тут нужно сделать? По идее, это всё должно быть зашито в сами компоненты
![image](https://user-images.githubusercontent.com/46089168/94688456-4ffc8a80-0336-11eb-8290-2a1e5f8f2a89.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
