### ISSUE TITLE
Маска даты

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#27]
Нужно поправить правила для валидации даты, сейчас можно некорректные значения вводить
![image](https://user-images.githubusercontent.com/46089168/94422668-1ee25580-0190-11eb-9e3e-1c36d81d51b1.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Стал меняться плейсхолдер при наведении, нужно вернуть тот, который был изначально там
![](https://i.imgur.com/5KcArip.gif)

**Comment by wirwl** [comment]
Исправил, можно проверять.
