### ISSUE TITLE
Ширина в %

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#28]
Это значение ширины похоже на подгонку под пиксель перфект, так относительные значения лучше не использовать, потому что придется снова эти % подгонять, если отступ изменится на, скажем, 10 пикселей. Тут все равно используются флексы, с которыми даже не надо напрягаться, достаточно задать margin между блоками и контейнеры займут сводобное место
![image](https://user-images.githubusercontent.com/46089168/94422925-7da7cf00-0190-11eb-9540-0a3d2e289a8c.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
На маленьких разрешениях теперь так, такое поведение задумывалось?
![image](https://user-images.githubusercontent.com/46089168/94574647-09e2f080-027c-11eb-999f-455c7a098e9e.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Еще раз, эти значения ширины 48% не нужны, margin решает эту проблему. Даже если сейчас просто выключить правило width: 48%, всё останется таким же, зачем оно там нужно?)

**Comment by wirwl** [comment]
Исправил, можно проверять.
