### ISSUE TITLE
Кнопки соцсетей

### ISSUE THREAD

**Issue by Fr0stmourne** [wirwl/ToxinHotel#29]
Разметку для этих кнопок надо создавать в цикле, их там может быть например 5 или 7 и придется копипастить эти классы. Еще было бы семантически лучше сделать контейнер списком ul, а ссылки обернуть в li
![image](https://user-images.githubusercontent.com/46089168/94574844-41519d00-027c-11eb-9615-18fc3c4165e9.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by Fr0stmourne** [comment]
Цвет кнопок в стилях есть в теме, его нужно оттуда взять

**Comment by wirwl** [comment]
Исправил, можно проверять.
