### ISSUE TITLE
Разное

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#3]
1. Сокращения в именовании лучше не использовать, даже очевидные.
![codestyle](https://user-images.githubusercontent.com/51824674/79353900-e3e3c100-7f65-11ea-8184-1792ce3f929b.png)
2. В pug-файлах использовать двойные кавычки.
![double quotes](https://user-images.githubusercontent.com/51824674/79353980-ff4ecc00-7f65-11ea-819c-ab964f727c9d.png)
3. Отделять импорты пробелами.
![space](https://user-images.githubusercontent.com/51824674/79354626-d7ac3380-7f66-11ea-8a27-6e0add225939.png)
4. Большинство внутренних импортов (js, scss) не прописывать, а делать автоматически (см. webpack dependency management).
![Безымянный](https://user-images.githubusercontent.com/51824674/79355063-68830f00-7f67-11ea-823f-10a73e946ce3.png)
5. В одной папке с компонентом один шаблон с одним миксином
![one mixin a file](https://user-images.githubusercontent.com/51824674/79355662-26a69880-7f68-11ea-9f8a-b3fcc4eaf4a7.png)
6. И название миксина должно совпадать с названием компонента
![naming](https://user-images.githubusercontent.com/51824674/79355873-71c0ab80-7f68-11ea-8d9a-c6b821471949.png)
7. В scss-файле должен быть один главный блок, другие в него вкладываются с помощью &
![one block at a top](https://user-images.githubusercontent.com/51824674/79356085-b8160a80-7f68-11ea-9d4c-eb772f27fd4e.png)
8. Общие классы со стилями не использовать, заменить scss-миксином/переменной, или везде прописывать вручную.

**Comment by wirwl** [comment]
Всё исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Фиксированную высоту не использовать, и вообще высоту лучше не использовать, кроме случаев, где это необходимо.
![height](https://user-images.githubusercontent.com/51824674/79874164-36aff380-8412-11ea-92dc-c04f8ede168e.png)
2. Сокращения не использовать.
![shortening](https://user-images.githubusercontent.com/51824674/79874190-3e6f9800-8412-11ea-8613-bfd059ca19a6.png)
3. Отрицательные margin не использовать.
![negative margin](https://user-images.githubusercontent.com/51824674/79874271-5810df80-8412-11ea-987a-7c2e65bf782f.png)

**Comment by wirwl** [comment]
Всё исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Сокращение из предыдущего замечания осталось, также есть еще
![shortening](https://user-images.githubusercontent.com/51824674/80857518-0c193280-8c7d-11ea-9406-707d1a03f8f8.png)
2. False
![term](https://user-images.githubusercontent.com/51824674/80857536-34a12c80-8c7d-11ea-9cfd-f279339e3415.png)
3. Медиазапросы использовать внутри правил бэм-блока во всем проекте
![one rule](https://user-images.githubusercontent.com/51824674/80857556-57cbdc00-8c7d-11ea-8320-c1f8aa02967d.png)
4. Здесь точно нужно увеличить приоритет?
![why priority](https://user-images.githubusercontent.com/51824674/80857575-6e723300-8c7d-11ea-985c-8057e154ff82.png)

**Comment by iatsdotfatr** [comment]
И еще, input оборачивай в label, for и id использовать только тогда, когда обернуть невозможно из-за расположения элементов.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Так работать не будет.
![doesnt](https://user-images.githubusercontent.com/51824674/81414342-089c1480-9171-11ea-80c8-4ed1a4322585.png)
2. 
![for id](https://user-images.githubusercontent.com/51824674/81414358-0fc32280-9171-11ea-93c9-439414d38963.png)
3. Отступы сделать как в других файлах.
![indents](https://user-images.githubusercontent.com/51824674/81414302-f7eb9e80-9170-11ea-9c64-12439f35bb11.png)
4. ?
![Безымянный](https://user-images.githubusercontent.com/51824674/81414689-8f50f180-9171-11ea-9e98-427e47e5ccdd.png)
5. Поправить селекторы.
![fix selectors](https://user-images.githubusercontent.com/51824674/81414578-63357080-9171-11ea-8acc-323cb41096af.png)

**Comment by wirwl** [comment]
Исправил, можно проверять. 
Правда 5й пункт, я не понял, что не так с селекторами? 
Такая комбинация селекторов мне нужна чтобы стилизовать первый уровень меню (горизонтальный) и вложенные (вертикальные) подменю.

**Comment by iatsdotfatr** [comment]
Просто используй модификаторы для вертикальных списков и ссылок, и никакие селекторы, кроме классовых, не понадобятся.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Так тоже не будет работать. Посмотри как в чекбоксе.
![doesnt](https://user-images.githubusercontent.com/51824674/82953885-c62e6080-9fd5-11ea-822d-7b763f92f0ba.png)
2. Оформление привести к одному виду, после двоеточия пробелы, объекты и массивы в несколько строк писать как в js, исправить во всех файлах проекта.
![styles](https://user-images.githubusercontent.com/51824674/82953989-0a216580-9fd6-11ea-8bad-fefbec7db10f.png)
3. Убрать for - id.
![for id](https://user-images.githubusercontent.com/51824674/82954040-1e656280-9fd6-11ea-8b2b-8bff9fd7912e.png)

**Comment by wirwl** [comment]
> 1. Так тоже не будет работать. Посмотри как в чекбоксе.
>    ![doesnt](https://user-images.githubusercontent.com/51824674/82953885-c62e6080-9fd5-11ea-822d-7b763f92f0ba.png)

А что работать не будет? Я не понял.

**Comment by wirwl** [comment]
> 3\. Убрать for - id.
>     ![for id](https://user-images.githubusercontent.com/51824674/82954040-1e656280-9fd6-11ea-8b2b-8bff9fd7912e.png)

Тут id и for нужны для реализации функционала без js, но с использованием css, они нужны для правильной работы комбинатора селекторов ~, т.е. я тут не могу input вложить в label.

Мне оставить id/for или убрать их (добавив необходимый код javascript)?

**Comment by iatsdotfatr** [comment]
JS.

**Comment by wirwl** [comment]
> 1. Так работать не будет.
>    ![doesnt](https://user-images.githubusercontent.com/51824674/81414342-089c1480-9171-11ea-80c8-4ed1a4322585.png)
А что тут не так? я не понял. Если не нужен заголовок просто тогда не будет вставляться соответствующий html тэг label.

**Comment by iatsdotfatr** [comment]
>     1. А что тут не так? я не понял. Если не нужен заголовок просто тогда не будет вставляться соответствующий html тэг label.

Input должен быть внутри label

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Случайные классы
![classes](https://user-images.githubusercontent.com/51824674/84514482-e86df100-acec-11ea-8a97-8198dbf88f37.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Другой цвет у фона.
![bgcolor](https://user-images.githubusercontent.com/51824674/85742539-245d7900-b725-11ea-9e45-710f89cbc4ff.png)
2. Расскоментировать или удалить.
![comments](https://user-images.githubusercontent.com/51824674/85742591-30e1d180-b725-11ea-908d-f1a7038def23.png)
3. Список должен закрываться при нажатии вне.
![dropdown close](https://user-images.githubusercontent.com/51824674/85742811-5d95e900-b725-11ea-952c-b7cc21fd739b.png)
4. Alt не указан.
![Screenshot from 2020-06-25 20-32-28](https://user-images.githubusercontent.com/51824674/85742971-7f8f6b80-b725-11ea-8adc-12caecd169d0.png)
5. Убрать пробелы.
![indents](https://user-images.githubusercontent.com/51824674/85743021-89b16a00-b725-11ea-86af-605d9899d973.png)
6. 
![Screenshot from 2020-06-25 20-33-54](https://user-images.githubusercontent.com/51824674/85743103-98981c80-b725-11ea-82b2-2c0e74a50c28.png)
![Screenshot from 2020-06-25 20-33-34](https://user-images.githubusercontent.com/51824674/85743119-9b930d00-b725-11ea-8c95-28778856c861.png)
![external](https://user-images.githubusercontent.com/51824674/85743142-9fbf2a80-b725-11ea-9f2a-9a0c9070b8de.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.
