### ISSUE TITLE
ComfortInput

### ISSUE THREAD

**Issue by MorganaLF** [wirwl/ToxinHotel#31]
Совершенно непонятный кусок кода, что тут происходит? Метод называется init, но на инициализацию это явно не похоже.
Много вложенных условий, что затрудняет чтение. Имена переменных совершенно непонятные, что за number2, number5? Что за count, счетчик чего именно? Что такое result, что в нём лежит? Всё это должно быть понятно из названий переменных.
Захардкоженные числа 0, 4, 1 тоже непонятно, откуда берутся, почему именно эти числа и что они значат. Они либо из настроек должны прилетать, либо из констант, если это какие-то неизменные значения.

![Снимок экрана от 2020-10-31 22-42-06](https://user-images.githubusercontent.com/38564412/97788523-96aa0280-1bca-11eb-9b8f-ce81608931ac.png)

**Comment by wirwl** [comment]
> Совершенно непонятный кусок кода, что тут происходит? Метод называется init, но на инициализацию это явно не похоже.

Тут плагин **item-quantity-dropdown** инициализируется: this._$iqdropdowns.iqDropdown({}); Просто тут ещё функция определяется для **setSelectionText** Я её вынес в отдельный метод, чтобы почитабелнее код был.

> Имена переменных совершенно непонятные, что за number2, number5?

Это множественное число, 2 спальни, 5 спален. Переименовал их.

Исправил, можно проверять.

**Comment by MorganaLF** [comment]
> Просто тут ещё функция определяется для setSelectionText.

Так single responsibility должно быть, об этом есть в стандартах) https://github.com/fullstack-development/front-end-best-practices/tree/master/JS#1.6
