### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by MorganaLF** [wirwl/ToxinHotel#32]
А где, собственно, класс DatepickerInput, инициализация плагина и т.д.?)

![Снимок экрана от 2020-10-31 22-50-48](https://user-images.githubusercontent.com/38564412/97788678-bbeb4080-1bcb-11eb-9edf-d5e6e9c2c414.png)

**Comment by wirwl** [comment]
Это вообщем лишний код и лишний файл, остался после многочисленых правок. Удалил файл.
