### ISSUE TITLE
Alt-текст

### ISSUE THREAD

**Issue by MorganaLF** [wirwl/ToxinHotel#34]
А зачем тут такой alt-текст? Какой он имеет смысл?

![Снимок экрана от 2020-11-23 22-00-05](https://user-images.githubusercontent.com/38564412/100003568-53ad0a80-2dd7-11eb-991d-5b4698aa5469.png)

**Comment by wirwl** [comment]
Просто, чтобы показывался номер картинки, при перелистывании слайдера: img-1, img-2.
Упростил текст в атрибуте alt.

**Comment by MorganaLF** [comment]
Дело в том, что у атрибута alt есть свое назначение - он нужен исключительно для описания изображения и служит для доступности контента. Если твой пользователь использует читалку, то текст " img-1" либо "image-slider" ему ни о чем не скажет, он не узнает, что было на картинке. Аналогично поисковики не проиндексируют правильным образом контент. Поэтому тут было правильнее передавать аргументом конкретный alt-текст, а не хардкодить его.
