### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#4]
1. Фиксированные размеры к блокам не применять
![block geometry](https://user-images.githubusercontent.com/51824674/79356409-1f33bf00-7f69-11ea-9ef6-7b339bf1b80a.png)
2. Каждый пользовательский класс в разметке является бэм-сущностью (за исключением классов для поиска в DOM). В шаблоне может быть только один главный блок с тем же названием, что и файл шаблона, другие блоки можно импортировать и вкладывать в главный, для позиционирования/геометрии
импортируемых блоков использовать бэм-элементы-обертки, для дополнительной стилизации бэм-модификаторы импортируемых блоков.
![one block](https://user-images.githubusercontent.com/51824674/79357820-b64d4680-7f6a-11ea-94cf-4c6ebe240aef.png)

**Comment by wirwl** [comment]
Вроде всё исправил.

**Comment by iatsdotfatr** [comment]
1. Несколько бэм-блоков в одном шаблоне. Цифры в именах классов также не использовать.
![numbers in classnames, many blocks](https://user-images.githubusercontent.com/51824674/79870243-e4200880-840c-11ea-8149-8a94e4ee418d.png)
2. В БЭМ, если нет необходимости (например, стилизация чекбокса), комбинировать селекторы только пробелом ( не >, ~, +), * в стилях блока не использовать вообще
![selectors](https://user-images.githubusercontent.com/51824674/79870765-ac659080-840d-11ea-8024-671a6f2ed8df.png)
3. Свойства внешнего позиционирования к блокам не применять, даже в такой форме
![block margin](https://user-images.githubusercontent.com/51824674/79870943-e6cf2d80-840d-11ea-8e3e-ac1020cff9e5.png)

**Comment by wirwl** [comment]
Всё исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Несколько бэм-блоков в одном шаблоне, проверить везде.
![two bem blocks](https://user-images.githubusercontent.com/51824674/80857446-84332880-8c7c-11ea-93c3-58a628586195.png)
![two bem blocks](https://user-images.githubusercontent.com/51824674/80857449-86958280-8c7c-11ea-87b7-669e543b953a.png)
2. Если надо изменить элемент, модификатор применять к элементу
![mods on els](https://user-images.githubusercontent.com/51824674/80857477-b47ac700-8c7c-11ea-9bc0-3ff67d168122.png)
3. В подобных случаях использовать модификатор типа 'ключ-значение'
![key-value modifier](https://user-images.githubusercontent.com/51824674/80857487-cd837800-8c7c-11ea-826d-5eb3d5b228eb.png)

**Comment by wirwl** [comment]
1. 
    .iqdropdown(class = isOpen ? 'menu-open' : '')
      p.iqdropdown-selection
      .iqdropdown-menu
        for item in [{id:'bedrooms', text: 'Спальни', count:2}, {id:'beds', text:'Кровати', count:2}, {id:'bathrooms', text:'Ванные комнаты'}]
          .iqdropdown-menu-option(data-id=item.id data-defaultcount=item.count)
            div: p.iqdropdown-item #{item.text}

Эта совакупность классов нужна для корректной работы jquery-плагина установленого через npm: **item-quantity-dropdown**. Причём этот код одинаков что в comfort-input, что в guests-input.  Как вариант могу его оформиться в виде миксина? И подключать в comfort-input и guests-input.

**Comment by iatsdotfatr** [comment]
Да.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Модификатор добавлять к элементу.
![mod on el](https://user-images.githubusercontent.com/51824674/81414041-962b3480-9170-11ea-9841-f6ba89da6553.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.
