### ISSUE TITLE
Компонентность

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#5]
Убрать хардкод, оставить только параметры функции.
![hardcode](https://user-images.githubusercontent.com/51824674/79871176-31e94080-840e-11ea-8908-c429e2887202.png)

**Comment by wirwl** [comment]
"хардкод" это всмысле жёстко прописаные параметры? То есть убрать type="button"? А если надо задать значение атрибуту type, например, то это передавать через параметры?

**Comment by iatsdotfatr** [comment]
Да, в миксинах только разметка и переменные.

**Comment by iatsdotfatr** [comment]
Data не используется, не надо ее писать, оставь только деструктурированный объект. Если слишком длинная строка получается, тогда в параметрах пиши data, а в теле деструктурируй.
![unused data](https://user-images.githubusercontent.com/51824674/80674012-ec4a0900-8ada-11ea-8d21-e12128316454.png)

**Comment by wirwl** [comment]
Всё исправил, можно проверять.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
В миксинах оставить только переменные, хардкод убрать.
![hardcode](https://user-images.githubusercontent.com/51824674/81413934-76940c00-9170-11ea-90a2-66d4288cf1c5.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Страницы тоже сделай миксинами, которые будут принимать параметры для всех вложенных в них миксинов, то есть убери страницы в компоненты, в папке со страницами оставь только паг-файлы, в которых подключенному миксину будет передаваться один объект с аргументами для всех миксинов внутри

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Аргументы во вложенные миксины также передавать из корневого миксина, то есть миксина страницы. Чтобы, например, если потребуется изменить язык страницы, это можно было сделать из одного места.

![comp](https://user-images.githubusercontent.com/51824674/82954390-d0049380-9fd6-11ea-807e-552816a5dc6d.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.
