### ISSUE TITLE
JS

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#7]
1. Все сторонние плагины подключать через npm
![plugins via npm](https://user-images.githubusercontent.com/51824674/79873347-2fd4b100-8411-11ea-9653-fdd24fc943c7.png)
2. Функциональный код переписать на ES6 классы, сторонние плагины также инициализировать через классы, и document.ready и т.п. не нужен, если скрипт подключается в конце body.
![es6 classe, docready](https://user-images.githubusercontent.com/51824674/79873730-ab366280-8411-11ea-88ea-60a75f4894c0.png)

**Comment by wirwl** [comment]
Всё исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. В идеале, в конструктор передать только один метод.
![lightweight consctructor](https://user-images.githubusercontent.com/51824674/80857144-f5251100-8c79-11ea-9cc4-8b2a5d65b3ec.png)
2. Методы называть camelcase'ом, использовать нижнее подчеркивание только как первый символ приватных методов (все, или почти все методы в данном проекте приватные или статические).
![no underscore](https://user-images.githubusercontent.com/51824674/80857242-ceb3a580-8c7a-11ea-9dd5-0e2cb16b1b7e.png)
3. Через npm
![plugin](https://user-images.githubusercontent.com/51824674/80857252-e4c16600-8c7a-11ea-82db-1807e0c53db7.png)
4. Добавить в eslint правила Airbnb, добавить в блок env jquery для избежания некоторых конфликтов с данными правилами, другие конфликты сверять с [best practices](https://github.com/fullstack-development/front-end-best-practices), если best practices их не перекрывают, исправлять. Также могут возникнуть конфликты с импортами jquery из node_modules типа 'unused vars' и связанные с мутацией переменных, содержащих DOM-узел, из можно игнорировать или использовать что-то вроде eslint-disable-next-line. Также ознакомиться с правилами [непосредственно](https://github.com/airbnb/javascript).

**Comment by wirwl** [comment]
drawDonutChart всмысле через npm? я его сам написал с нуля.

**Comment by iatsdotfatr** [comment]
Тогда перепиши на класс, и IIFE в модулях не надо использовать.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Импорты из node_modules, по возможности, делать абсолютными.
![imports](https://user-images.githubusercontent.com/51824674/81413708-1604cf00-9170-11ea-842c-aedc9b1c31b7.png)
2. Именование обработчиков.
![handle](https://user-images.githubusercontent.com/51824674/81413771-303ead00-9170-11ea-8f5d-ff8f54c1be55.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1.  Посмотреть везде
![event-h](https://user-images.githubusercontent.com/51824674/81902422-50e08a00-95ea-11ea-974e-d529e9272bd4.png)
![event-h1](https://user-images.githubusercontent.com/51824674/81902447-55a53e00-95ea-11ea-9d24-ba87e2420f40.png)
2. Сокращение, и вообще, зачем здесь, и в других местах использовать нэймспэйсы?
![event](https://user-images.githubusercontent.com/51824674/81902565-84bbaf80-95ea-11ea-9fa0-f56ad70d2aa8.png)

**Comment by wirwl** [comment]
> 2\. Сокращение, и вообще, зачем здесь, и в других местах использовать нэймспэйсы?
>     ![event](https://user-images.githubusercontent.com/51824674/81902565-84bbaf80-95ea-11ea-9fa0-f56ad70d2aa8.png)

Изначально не было неймспейсов. Читая бест-практик от FSD добавил их:
![фвыа](http://dl4.joxi.net/drive/2020/05/15/0001/0525/74253/53/9c8ed9f81a.jpg)

Хотя может что-то не так понял в этом пункте... Мне оставить неймспейсы или удалить?

**Comment by iatsdotfatr** [comment]
Здесь имеется ввиду не использовать анонимные функции в качестве обработчиков, чтобы можно было делать off/removeEventListener, удаляй.

**Comment by Znack** [comment]
> Здесь имеется ввиду не использовать анонимные функции в качестве обработчиков, чтобы можно было делать off/removeEventListener, удаляй.

ну вообще тут как раз про неймспейсы, не про то, какие функции в качестве обработчиков накидываются :)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
> 
> 
> > Здесь имеется ввиду не использовать анонимные функции в качестве обработчиков, чтобы можно было делать off/removeEventListener, удаляй.
> 
> ну вообще тут как раз про неймспейсы, не про то, какие функции в качестве обработчиков накидываются :)

Название пункта сбило меня с толку).
