### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#8]
1. Дропдаун ломается, если нажать на "Очистить". Также у большого дропдауна нижняя граница с закругленными углами, как и у выпадающего списка обоих дропдаунов. Кнопка "Очистить" должна появляться только когда хотя бы одно из значений больше единицы. Дропдаун должен закрываться при нажатии на экране вне дропдауна, не должен закрываться при нажатии на выпадающий список, если это не кнопка "Применить".
2. Предполагается, что это один календарь на два поля.
![cal](https://user-images.githubusercontent.com/51824674/82954868-ccbdd780-9fd7-11ea-88c3-e70e7830b8c2.gif)
3. Здесь другой цвет у фона.
![color](https://user-images.githubusercontent.com/51824674/82954914-e0693e00-9fd7-11ea-9dcf-2c92c156c4bc.png)
4. Граница у лайка градиентная, как и у звезды, как и у иконок элементов "Комфорт, Удобство".
5. Цена не указана.
![price](https://user-images.githubusercontent.com/51824674/82955141-5f5e7680-9fd8-11ea-87d6-1a61cba2875c.png)
6. Рейтинг не работает, отзывы лучше сделать ссылкой.
![rating link](https://user-images.githubusercontent.com/51824674/82955183-7604cd80-9fd8-11ea-9175-6e066dcc0422.png)
7. Уменьшать прозрачность ссылок при наведении
![ховер](https://user-images.githubusercontent.com/51824674/82955246-9cc30400-9fd8-11ea-85ef-b8d3b2272e34.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. Будет хорошо, если в дропдауне кнопки +/- будут изменять положение только если для числа будет недостаточно места.
2. В третьем пункте предыдущего коммента имелась ввиду пагинация, ее тоже надо подправить.
3. У границы лайк-кнопки в градиенте другие цвета.
4. При наведении на ссылку в карточке, нижняя линия разрывается, можно или заполнить разрыв с помощью before/after, или при наведении показывать нижний border при наведении, или как-нибудь еще.
5. Предполагается, что все ссылки в проекте меняют цвета при наведении.

В слайдере у загружаемых картинок url сломался.

**Comment by wirwl** [comment]
> 3\. У границы лайк-кнопки в градиенте другие цвета.
Точно помню что правил границы у лайк-кнопки и в коммите эти изменения есть: https://github.com/wirwl/ToxinHotel/commit/f0f3dd422649c98048bb2ca53640df73151a7e3d?diff=split
Но при build и deploy куда-то улетучился код. ))
Ну да ладно, ещё раз добавлю.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Разная прозрачность шрифта
![Screenshot from 2020-06-20 17-38-34](https://user-images.githubusercontent.com/51824674/85200892-ef17ec00-b31c-11ea-8db8-919ff9f6b2b5.png)
