### ISSUE TITLE
Pixel perfect

### ISSUE THREAD

**Issue by iatsdotfatr** [wirwl/ToxinHotel#9]
Исправить на всех страницах.
![Screenshot from 2020-06-12 20-39-32](https://user-images.githubusercontent.com/51824674/84514685-3c78d580-aced-11ea-8402-86b4fd6fb6a6.png)
Насколько знаю, некоторые макеты на фигме изменили, лучше перекачать оттуда картинки и править уже по ним, у меня старых картинок не осталось.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
1. В целом, страницы немного едут, сделай выравнивание при совпадении логотипа
 один-в-один.
![logo](https://user-images.githubusercontent.com/51824674/84794904-ab6d6b80-b018-11ea-8841-f3d852fc304f.png)
Также обнови ветку gh-pages, чтобы я на разных ОС посмотрел, иногда проблема бывает в этом.
2. Из ui-kit точно едет header-footers. В colors-types пункт body тоже не совпадает.
![h-f](https://user-images.githubusercontent.com/51824674/84795126-e7a0cc00-b018-11ea-881e-76b2b758e153.png)
3. По карточкам:

    - В регистрационной небольшое несоответствие содержимого с границами
![reg](https://user-images.githubusercontent.com/51824674/84795717-a9f07300-b019-11ea-91c6-7ced85e068bc.png)

   - В слайдере не совпадают точки
![dots](https://user-images.githubusercontent.com/51824674/84795830-cab8c880-b019-11ea-9835-02e1273ea8d7.png)

   - Немного съезжают формы
![Screenshot from 2020-06-16 21-25-38](https://user-images.githubusercontent.com/51824674/84796009-fb98fd80-b019-11ea-924d-5ce73facefb3.png)

- В бронировании 
![room](https://user-images.githubusercontent.com/51824674/84796215-31d67d00-b01a-11ea-83e6-0a660d038604.png)

- Содержимое календаря тоже надо немного сместить

![Screenshot from 2020-06-16 21-26-29](https://user-images.githubusercontent.com/51824674/84796296-46b31080-b01a-11ea-9c51-56e07a813284.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

Не во всех местах достиг "нанопиксельной" точности, но я думаю это не критично.

**Comment by iatsdotfatr** [comment]
1. В search room пагинация едет.
![pagination](https://user-images.githubusercontent.com/51824674/85199610-ba9f3280-b312-11ea-9b8d-8c0b7a6acf81.png)
2. На страницах (т.е. не ui-kit) при больших разрешениях фон и картинки растягивай на весь экран (на 1440px картинки должны быть pixel perfect), содержимое можно оставить в пределах 1440px.
![Screenshot from 2020-06-20 16-27-21](https://user-images.githubusercontent.com/51824674/85199707-81b38d80-b313-11ea-850a-0c0ca8b890c2.png)

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Рассинхрон в room-details, landing, и подвале
![room](https://user-images.githubusercontent.com/51824674/85741348-27a43500-b724-11ea-8ab6-6c2fdefbed70.png)
![landing](https://user-images.githubusercontent.com/51824674/85741361-2b37bc00-b724-11ea-920d-53b0ea3f7b33.png)
![footer](https://user-images.githubusercontent.com/51824674/85741374-2d9a1600-b724-11ea-9ef7-5e309e1df90c.png)

**Comment by wirwl** [comment]
> Рассинхрон в room-details, landing, и подвале
> ![room](https://user-images.githubusercontent.com/51824674/85741348-27a43500-b724-11ea-8ab6-6c2fdefbed70.png)
Нету рассинхрона. Пиксельпёрфект идеален, пруфы: http://joxi.ru/5mdV3aI3LZvbA1
То смещение которое ты наблюдаешь равно ширине вертикального скролла, которые естественно присутствует ввиду того что страница большая по высоте. Просто смотри пиксель пёрфект на ширине 1440 пикселей, без вертикального скролла.

**Comment by wirwl** [comment]
Вроде исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
Карточки немного съехали:
![Screenshot from 2020-06-30 19-01-32](https://user-images.githubusercontent.com/51824674/86133101-abd23000-bb09-11ea-9953-19a3345ed558.png)
![Screenshot from 2020-06-30 19-12-26](https://user-images.githubusercontent.com/51824674/86133111-af65b700-bb09-11ea-83fc-8170ba9de944.png)

Sign in тоже.

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
![Screenshot from 2020-07-02 12-45-42](https://user-images.githubusercontent.com/51824674/86327088-7beb6f80-bc64-11ea-8e4c-aeb73494a132.png)

**Comment by wirwl** [comment]
У меня всё нормально в room-details, смещения нет, может у тебя в плагине пару пикселей по вертикали смещение выставленно? Пруф: http://joxi.ru/J2boaKI0W174A6

**Comment by wirwl** [comment]
Исправил, можно проверять.

**Comment by iatsdotfatr** [comment]
> У меня всё нормально в room-details, смещения нет, может у тебя в плагине пару пикселей по вертикали смещение выставленно? Пруф: http://joxi.ru/J2boaKI0W174A6

Это из-за разных ОС скорее всего

**Comment by wirwl** [comment]
Исправил, можно проверять.
